### ISSUE TITLE
regions.py wx dependency

### ISSUE THREAD

**Issue by ConstantineLignos** [VerifiableRobotics/LTLMoP#13]
How hard is it to break the wx python dependency? I ask because I suspect the only way I'll ever be able to run simulation is in 64-bit. If the simulation is 64-bit but regions requires wx (32-bit), then the simulation can't run.

**Comment by cfinucane** [comment]
Shouldn't be too bad.  Working on this now.

**Comment by cfinucane** [comment]
This should be possible now, as of commit 50ef66834b3cf32b37bbfde00871c68035e3ca2d.

You would just need to make sure that `lib/execute.py` gets called from the 64-bit python (called as a subprocess from `specEditor.py:onMenuSimulate()`), and everything else continues with 32-bit for the wxpython support.
