### ISSUE TITLE
speceditor last line of text flickers on ubuntu

### ISSUE THREAD

**Issue by cfinucane** [VerifiableRobotics/LTLMoP#30]

**Comment by cfinucane** [comment]
Fixed for OS X as of 0cc8098d788e6afaa25ae8cd128eba273ef3eb5e.  Awaiting confirmation for Ubuntu.

**Comment by matteblair** [comment]
Can confirm issue fixed on Ubuntu 12.04!

**Comment by cfinucane** [comment]
Oh, wow, thanks!  Closing this, finally.

:dog2: :dog2: :dog2:
