### ISSUE TITLE
Issue with hideandseek.spec 

### ISSUE THREAD

**Issue by jamiesternlicht** [VerifiableRobotics/LTLMoP#39]
Decomposing map into convex regions...
Creating LTL...
    ERROR(8): Could not parse the sentence in line 31 because between is not recognized

```
ERROR(6): Could not parse the condition in line 31
```

ERROR: Aborting compilation due to syntax error.

**Comment by cfinucane** [comment]
Should be fixed by 601f0f58f211c9db73
