### ISSUE TITLE
Bare LTL compilation in speceditor fails

### ISSUE THREAD

**Issue by ConstantineLignos** [VerifiableRobotics/LTLMoP#43]
It looks like all spec compilation fails when the parser mode is LTL. For example, opening example/firefighting/specInLTL.spec, in the development or gumbo branches and compiling leads to:

<pre>
Decomposing map into convex regions...
    Traceback (most recent call last):
      File "specEditor.py", line 1068, in onMenuCompile
            compiler._decompose()
      File "lib/specCompiler.py", line 115, in _decompose
            self.parser.proj.rfi.writeFile(filename)
      File "lib/regions.py", line 368, in writeFile
            self.regions[region1 + 1 + region2].name] +
    IndexError  :   list index out of range 
</pre>

Changing the decomposition options in the spec file and menu doesn't seem to have an effect, but I'm not sure I've tried every possible combination.

**Comment by cfinucane** [comment]
b97d363f03b works around this issue.   The underlying bug here (inconsistent notions of what "enable-decompose" and "disable-decompose" mean in different places), however, will be addressed in an upcoming large-scale update.
