### ISSUE TITLE
Simulated robot doesn't go anywhere

### ISSUE THREAD

**Issue by ConstantineLignos** [VerifiableRobotics/LTLMoP#44]
When I open the spec at:
https://github.com/LTLMoP/LTLMoP/blob/93ac8f2de5068506b56777aed1400271d8f2c960/src/examples/ltlworkshop/patrol.spec

When I simulate, the robot doesn't go anywhere, I just see this in the log:

<pre>
[13:15:00] (Basic Simulator) Initializing Basic Simulator...
[13:15:00] (Basic Simulator) Start Basic Simulator...
[13:15:00] (SENS) Starting sensorHandler window and listen thread...
[13:15:01] (SENS) Starting actuatorHandler window...
[13:15:01] Loaded 96 states.
[13:15:01] Start!
[13:15:02] (ACT) Actuator extinguish is now 0!
[13:15:02] (ACT) Actuator radio is now 0!
[13:15:02] Currently pursuing goal #20 
</pre>

Before, something like this was traced to convex decomposition being off, but I've turned that on. The only difference between this and the LTL spec in firefighting us turning bit encoding on. I've tried with convex decomposition on and off, and both seem to show this problem. I'm testing on Windows, in case it matters.

**Comment by cfinucane** [comment]
The spec tells it to go to `porch` **or** `living`.  The basicsim config for that example starts the robot in `porch`, so it doesn't need to move to satisfy the goal.  Changing the initial region to something other than those 2 regions makes it move for me, as expected.  Or am I misunderstanding something?

P.S. The fact that your log says "`goal #20`" looks like an actual bug, but I can't reproduce it.

**Comment by ConstantineLignos** [comment]
DERP

Yeah, because there was a previous issue where the robot couldn't go anywhere when convex decomp. was off, when I saw this I assumed this was related to that problem again and didn't bother to check the spec.

The 20 was github; it parsed it as an issue number and tried to autocomplete it when I pasted, and I thought I stopped it but it picked its best match.
