### ISSUE TITLE
handlers in robot files could not be loaded

### ISSUE THREAD

**Issue by garthbjerk** [VerifiableRobotics/LTLMoP#51]
I am attempting to use a nao robot in the execution environment but it appears the handlers for most robot types could not be loaded from .robot file in handlerSubsystem.py. Do I need to create custom handlers or are these available somewhere? Namely, the init handler is missing for the nao robot. Looking at the _init_ python file in lib/handlers/robots/nao gives me a blank file.

**Comment by cfinucane** [comment]
Do you have the Python SDK for the Nao installed?  You can check this by seeing whether a plain `import naoqi` succeeds in an interactive Python session.

`__init__.py` files are generally always blank, so that should be unrelated (see http://stackoverflow.com/questions/448271/what-is-init-py-for)

**Comment by garthbjerk** [comment]
Hi,

After installing the Nao Python SDK, I am able to select the NAO robot.
Thanks for the information. Yet, once I go to run the simulation, there are
connection problems. Attached are the status log messages.

Garth

**Comment by cfinucane** [comment]
It looks like you are trying to use the Vicon pose handler (the default setting for the Nao), but I imagine that this is not what you want (or, at the very least, the IP address needs to be configured to something appropriate for your setup).   You can try the NullPose pose handler if you just want to get the Nao doing something, though.

**Comment by garthbjerk** [comment]
Thanks for the help. It appears there is no virtual simulator for the Nao
though? I'll have to wait until I can get back in the robotics lab here. If
this ticket is still open you can close it.

On Mon, Dec 16, 2013 at 11:50 AM, Cameron Finucane <notifications@github.com

**Comment by cfinucane** [comment]
Yeah, it would be great if someone implemented support for Webots or something eventually :)  Closing.
