### ISSUE TITLE
Remove "Spider" folder within handlers

### ISSUE THREAD

**Issue by itwasabhi** [VerifiableRobotics/LTLMoP#63]
Unable to run ConfigureSimulation or Simulate unless deleting the "Spider" directory

**Comment by jimjing** [comment]
fixed in bf75cd11a6fd7118c8948a5493b77b2ba3564e38

**Comment by cfinucane** [comment]
That commit is a 404 for me.  Are you sure you have the right ID?

**Comment by jimjing** [comment]
it is fine for me
https://github.com/LTLMoP/LTLMoP/commit/bf75cd11a6fd7118c8948a5493b77b2ba3564e38

**Comment by cfinucane** [comment]
Weird I guess github glitches out.  Thanks.
