### ISSUE TITLE
Mopsy/Counterstrategy not working in refactored development

### ISSUE THREAD

**Issue by spmaniato** [VerifiableRobotics/LTLMoP#71]
Mospy says module (fsa) has no attribute 'Automaton'.

<pre><code>Traceback (most recent call last):
  File "/Users/smaniato/Cornell/My Research/LTLMoP/src/etc/utils/mopsy.py", line 654, in <module>
    mopsy_frame = MopsyFrame(None, -1, "")
  File "/Users/smaniato/Cornell/My Research/LTLMoP/src/etc/utils/mopsy.py", line 164, in __init__
    self.env_aut = fsa.Automaton(self.proj)
AttributeError: 'module' object has no attribute 'Automaton'</code></pre>

Thanks!

**Comment by cfinucane** [comment]
Yeah, sorry, I’m working on this.

**Comment by cfinucane** [comment]
Should be fixed as of ed214f2abc56ee62d6525975d844bb3ce755ee44.  Let me know if you have any more problems.
