### ISSUE TITLE
Harware interface to robot

### ISSUE THREAD

**Issue by Bama-S** [VerifiableRobotics/LTLMoP#78]
Will this kit work for interfacing the real robot as well? If so, which part of the code should be modified?

**Comment by spmaniato** [comment]
Hi Bama,

you can control real robots via LTLMoP by writing the appropriate "handlers". See the existing ones for guidance: https://github.com/LTLMoP/LTLMoP/tree/development/src/lib/handlers

And here's some info on the handler subsystem: https://github.com/LTLMoP/LTLMoP/wiki/Handler-Subsystem

Finally, here's a video demonstrating LTLMoP (features control of a Aldebaran Nao humanoid): http://www.youtube.com/watch?v=M5gxI9sZKHg

Best,
Spyros
